version: '3.5'

services:

  traefik:
    image: "traefik:v2.1.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/home/centos/acme.json:/acme.json"                   # let's encrypt certificates
      - "/var/run/docker.sock:/var/run/docker.sock:ro"        # docker socket for traefik monitoring
      - "/home/centos/traefik.toml:/etc/traefik/traefik.toml" # traefik config
      - "/home/centos/traefik.log:/var/log/traefik.log"       # traefik logs
      - "/home/centos/access.log:/var/log/access.log"         # traefik access log
    networks:
      - dgserv3_network

networks:
  dgserv3_network:
    name: dgserv3_network


