version: '3.5'

services:
  goalblog:
    image: goal_blog:latest
    container_name: goalblog

    labels:
      # tells traefik to route traffic with Host goals.${DOMAIN} to goalblog
      - "traefik.http.routers.goalblog.rule=Host(`goals.${DOMAIN}`)"
      # enable automatic certificate generation
      - "traefik.http.routers.goalblog.tls.certresolver=le"
      - "traefik.http.routers.goalblog.entrypoints=websecure"
      # tell traefik to use different port
      - "traefik.http.services.goalblog.loadbalancer.server.port=8080"
      # use dgserv3
      - "traefik.docker.network=dgserv3"

    restart: unless-stopped

    networks:
      - dgserv3

networks:
  dgserv3:
    name: dgserv3
    external: true
