version: '3.5'

services:
  whoami:
    image: "containous/whoami"
    container_name: whoami

    labels:
      # tells traefik to route traffic with Host whoami.${DOMAIN} to whoami
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      # enable automatic certificate generation
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # use dgserv3_network
      - "traefik.docker.network=dgserv3_network"

    restart: unless-stopped

    networks:
      - dgserv3_network

networks:
  dgserv3_network:
    name: dgserv3_network
    external: true
