version: '3.5'

services:
  whoami:
    image: "containous/whoami"
    container_name: whoami

    labels:
      # tells traefik to route traffic with Host whoami.${DOMAIN} to whoami
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      # enable automatic certificate generation
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # use dgserv3
      # - "traefik.docker.network=dgserv3"

    restart: unless-stopped

    networks:
      - dgserv3

networks:
  dgserv3:
    name: dgserv3
    external: true
