version: '3.5'

services:

  bookstack:
    image: solidnerd/bookstack:0.27.5
    container_name: bookstack
    networks:
      - internal
      - dgserv3
    depends_on:
    - bookstack-db
    environment:
    - DB_HOST=bookstack-db:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=bookstack
    - APP_URL=https://bookstack.${DOMAIN}
    volumes:
    - /home/centos/bookstack/data/uploads:/var/www/bookstack/public/uploads
    - /home/centos/bookstack/data/storage-uploads:/var/www/bookstack/storage/uploads
    labels:
      # tells traefik to route traffic with Host bookstack.${DOMAIN} to bookstack
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.${DOMAIN}`)"
      # enable automatic certificate generation
      - "traefik.http.routers.bookstack.tls.certresolver=le"
      - "traefik.http.routers.bookstack.entrypoints=websecure"

      # - traefik.enable=true
      # - traefik.docker.network=traefik_web
      # - traefik.http.services.bookstack-bookstack.loadBalancer.server.port=80
      # - traefik.http.routers.bookstack.entrypoints=websecure
      # - traefik.http.routers.bookstack.tls.certresolver=le
      # - traefik.http.routers.bookstack.rule=Host(`XXZ`)

  bookstack-db:
    image: mariadb:10.4.8
    container_name: bookstack-db
    networks:
      - internal
    environment:
    - MYSQL_ROOT_PASSWORD=bookstack
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=bookstack
    volumes:
    - /home/centos/bookstack-db:/var/lib/mysql
















#   bookstack:
#     image: "linuxserver/bookstack"
#     container_name: bookstack
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=America/Chicago
#       - DB_HOST=bookstack_db
#       - DB_USER=bookstack
#       - DB_PASS=yourdbpass
#       - DB_DATABASE=bookstackapp
#     volumes:
#       - /home/centos/bookstack/config:/config
#     ports:
#       - 6875:80
#     restart: unless-stopped
#     depends_on:
#       - bookstack_db
#     labels:
#       # tells traefik to route traffic with Host bookstack.${DOMAIN} to bookstack
#       - "traefik.http.routers.bookstack.rule=Host(`bookstack.${DOMAIN}`)"
#       # enable automatic certificate generation
#       - "traefik.http.routers.bookstack.tls.certresolver=le"
#       - "traefik.http.routers.bookstack.entrypoints=websecure"
#     networks:
#       - dgserv3

#   bookstack_db:
#     image: linuxserver/mariadb
#     container_name: bookstack_db
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - MYSQL_ROOT_PASSWORD=yourdbpass
#       - TZ=Europe/London
#       - MYSQL_DATABASE=bookstackapp
#       - MYSQL_USER=bookstack
#       - MYSQL_PASSWORD=yourdbpass
#     volumes:
#       - /home/centos/bookstack_db/config:/config
#     networks:
#       - dgserv3

networks:
  internal:
    driver: bridge
  dgserv3:
    name: dgserv3
    external: true
