version: '3.5'

services:
  bookstack:
    image: "linuxserver/bookstack"
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/centos/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      # tells traefik to route traffic with Host bookstack.${DOMAIN} to bookstack
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.${DOMAIN}`)"
      # enable automatic certificate generation
      - "traefik.http.routers.bookstack.tls.certresolver=le"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
    networks:
      - dgserv3

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - /home/centos/bookstack_db/config:/config
    networks:
      - dgserv3

networks:
  dgserv3:
    name: dgserv3
    external: true
