version: '3.5'

services:
  heyo:
    image: heyo_world:latest
    container_name: heyo

    labels:
      # tells traefik to route traffic with Host heyo.${DOMAIN} to heyo
      - traefik.http.routers.heyo.rule=Host(`heyo.${DOMAIN}`)
      # enable automatic certificate generation
      - traefik.http.routers.heyo.tls.certresolver=le
      - traefik.http.routers.heyo.entrypoints=websecure

    restart: unless-stopped

    networks:
      - dgserv3

networks:
  dgserv3:
    name: dgserv3
    external: true
